/** Stamp a demo page as a preview, at the moment it is served.
 *
 * The demo carries a real business's name, address, phone and trading hours,
 * and it answers to anyone holding the link. Everything else about it is built
 * to be convincing — that is the point of the pitch — which is exactly why it
 * has to say what it is on its face.
 *
 * Injected here rather than written into the page for one reason: the demo
 * HTML is generated by a model from an art-direction brief, and a model can
 * drop anything. The `stock_note` line lives in the templates and needs a
 * `missing_stock_note` check to catch the times it goes missing. A disclosure
 * about whose site this is not should not depend on a check remembering to
 * run. The response is ours; the document is not. Same reasoning that puts
 * `x-robots-tag` on the response alongside the meta tag.
 *
 * `position: fixed` rather than sticky or static. Static loses to any fixed
 * header the page happens to have — the banner would be sitting underneath it,
 * invisible, at exactly the scroll position where it matters most. Sticky
 * would be the tidier choice but `html { overflow-x: hidden }` breaks it, and
 * warm_minimal sets precisely that to contain a full-bleed strip. Fixed plus a
 * padding rule on body is the one arrangement that survives all fourteen art
 * directions and whatever a model invents beyond them.
 *
 * The z-index is the maximum a 32-bit signed int allows, and deliberately so:
 * when the banner and the design disagree about who is on top, the banner
 * wins.
 *
 * No JavaScript, because the response's CSP allows none — the banner cannot be
 * dismissed, which is the correct behaviour for it anyway.
 */

const BANNER_ID = "loom-preview-notice";

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** The notice, as markup. Exported for the test, not for callers. */
export function previewNotice(business: string | null | undefined): string {
  // Naming the business is what makes the sentence do its job: "not the
  // official site" is a much weaker claim when the reader has to work out
  // which site is being disclaimed.
  const who = business?.trim() ? escapeHtml(business.trim()) : "this business";

  return (
    `<style>` +
    // !important because the page sets its own body rules and this one is not
    // negotiable. The wider value on narrow screens is for the second line the
    // sentence wraps onto there.
    `body{padding-top:2.5rem !important}` +
    `@media(max-width:620px){body{padding-top:3.5rem !important}}` +
    `</style>` +
    `<div id="${BANNER_ID}" role="note" style="` +
    `position:fixed;top:0;left:0;right:0;z-index:2147483647;` +
    `box-sizing:border-box;padding:.55rem 1rem;` +
    // Its own type stack and colours: the page's fonts and palette are the
    // thing being previewed, and a notice wearing them reads as part of it.
    `background:#1f2328;color:#f6f8fa;` +
    `font:400 13px/1.45 -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;` +
    `text-align:center;letter-spacing:.01em` +
    `">` +
    `Design preview — not the official website of ${who}, ` +
    `and not published by them.` +
    `</div>`
  );
}

/** Serve-time injection. Returns the document with the notice inside <body>. */
export function withPreviewNotice(
  html: string,
  business: string | null | undefined
): string {
  const notice = previewNotice(business);

  // After the opening body tag, so the notice is inside the element its
  // padding rule applies to. The tag may carry attributes, and a generated
  // document occasionally has none at all — hence the fallback rather than a
  // thrown error, because a demo that renders without the notice is worse
  // than one whose notice sits above <html>.
  const bodyOpen = /<body\b[^>]*>/i.exec(html);
  if (bodyOpen) {
    const at = bodyOpen.index + bodyOpen[0].length;
    return html.slice(0, at) + notice + html.slice(at);
  }
  return notice + html;
}
